
language: cpp

dist: trusty

sudo: false

cache:
  apt: true

before_install:
  - sudo add-apt-repository ppa:jonathonf/gcc -y
  - sudo add-apt-repository ppa:jonathonf/perl6 -y # for libuv1
  - sudo apt-get update -q

addons:
  apt:
    update: true    
    packages: &default_packages
      - cmake
      - build-essential
      - wget
      
install:
  - sudo apt-get install -f libuv1-dev gcc-8 g++-8 cmake3 -y --allow-unauthenticated
  - mkdir build 
  - cd build
  - wget https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-latest.tar.gz
  - tar -xf libmicrohttpd-latest.tar.gz
  - cd libmicrohttpd*
  - ./configure --disable-shared --disable-doc --disable-examples --disable-curl --enable-https=no --disable-bauth --disable-dauth --disable-httpupgrade
  - make
  - sudo make install
  - cd ..

script:

  - cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a -DMHD_LIBRARY=/usr/local/lib/libmicrohttpd.a 
  - make
  - cd ..
  - tar czvf webchain-miner-ubuntu14_04.tar.gz "build/webchain-miner" "src/*config*"

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Command"
  - git config --local user.email "maoxs2@163.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: 
    secure: "J3E144SB3vF6lN+ROJalbkZeHRX3XAkFSxKdXuxOmHr6j/yav1+UPMQ1mKqXVK23+Wjg5Yfz6OKvyxB25dyJx90XHrbftkMXcvVuu/Re9I0Bqc+J83SWML8dIabSyjf/Q2K30rsken47elUCbYGWiAPTRyS0/SZjly89dIcjBqbIhdsqPWrL5Pl5exJigLj1+v3RTDlyzfpDHwqQ4qBuG3+RfK/ca5mYeCODgxbEdtazdN1hlWKwwrmvjpMc9qio4gYhIfrpdUhNLIRIkHQqHd83rDYjkryAR33XSeE8usETjIhEbnYRFz8FK7Jl2j7Plrgp7PYSuKFUd8Ev+sxPNzlaGS9r5/2+2mdavhgJmBttLRoNzroOBIr0/TaYhfrlPoWPHZc6MSWvlKt5T3CTNRTLLyAmlssV9gby0ii398e+J32sRGMq8pegi9kQ/iFrJvrSaVH96kr4Ijdp8DQeTvj4PhdKRJHdFJJNsnTR9AP+4nJEgvytz2JeEj6QFay5J+RK8Wj1IhPykm1wPXr6j3ap0FmpG+89Leq5h+HJ6xMxD+HKoa6mgxyPvAOCHhuUO2j9xdpZJGekWbrjHVfqhnvVEHUEve/zZz53a2onvqyUFLAzXpXuihqDnKhJK/2153ayRh7cTgwDlzN1eW9l63+Zpb4KXUVPKrQKPOSdQmw="
  file: webchain-miner-ubuntu14_04.tar.gz
  skip_cleanup: true
  on:
    tags: true
    
