
language: cpp

dist: trusty

sudo: false

cache:
  apt: true

before_install:
  - sudo add-apt-repository ppa:jonathonf/gcc -y
  - sudo add-apt-repository ppa:jonathonf/perl6 -y # for libuv1
  - sudo apt-get update -q

install:
  - sudo apt-get install -f libmicrohttpd10 libuv1 build-essential gcc-8 g++-8 cmake -y


script:
  - mkdir build 
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.so -DMHD_LIBRARY=/usr/lib/x86_64-linux-gnu/libmicrohttpd.so.10
  - cd ..

after_script:
  - tar czvf webchain-miner-ubuntu14_04.tar.gz "build/webchain-miner" "src/*config*"

# before_deploy:
#   # Set up git user name and tag this commit
#   - git config --local user.name "YOUR GIT USER NAME"
#   - git config --local user.email "YOUR GIT USER EMAIL"
#   - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true