# version format
version: 1.0.{build}

# build only tags
skip_non_tags: true

# image
image: Visual Studio 2017

# build platform
platform: x64
configuration: Release

# clone directory
clone_folder: c:\xmrig

install:
  - mkdir c:\xmrig-deps
  - curl -sL https://github.com/xmrig/xmrig-deps/archive/v3.1.zip -o xmrig-deps.zip
  - 7z x xmrig-deps.zip -o"c:\" -y > nul

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\xmrig
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DXMRIG_DEPS=c:\xmrig-deps-3.1\msvc2017\x64
  - msbuild webchain-miner.sln /p:Configuration=Release

after_build:
- cd c:\xmrig
- cmd: 7z a webchain-miner-win64.zip "c:\xmrig\build\Release\*.exe" "c:\xmrig\src\*config*" "c:\xmrig\src\*.bat*" "c:\xmrig\src\*.txt*"
- cmd: dir

artifacts:
- path: webchain-miner-win64.zip
